#!/usr/bin/env python3
"""Regenerate the top-level aggregate tables from chains/*/chain.yaml.

Ethereum Mainnet is the Schelling point: every row is a delta against it.
Stack nodes (role: stack) are resolved into their descendants so aggregate
tables show each chain's complete effective set, with origin marked.

Loading, ordering and address canonicalisation live in `model.py`, shared with
`site.py`, so the Markdown tables and the website cannot disagree about them.
"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from model import (ROOT, CHAINS, ORDER, SHORT, MARK, load, name, documented,
                   client, is_stack, order, canon, addr_rows, sortkey,
                   entry_label, eip_status, tx_auth)

def cell(entry, this_slug, org):
    if entry is None: return ""
    s = MARK.get(entry.get("status", "inherited"), entry.get("status", ""))
    if entry.get("availability") == "optional": s += "◐"
    if entry.get("tombstoned_at"): s += "⏳"
    if entry.get("pending_conflict"): s += "‼️"
    if org and org != this_slug: s += "†"
    return s

def header(chains, slugs):
    h = "| Address | " + " | ".join(SHORT.get(s, name(chains[s])) for s in slugs) + " |"
    return h + "\n|" + "---|" * (len(slugs) + 1)

def write(path, text):
    (ROOT / path).write_text(text)
    print(f"  wrote {path} ({len(text.splitlines())} lines)")

def legend():
    return ("\nLegend: ➕ added · ➖ removed / never adopted · ⚠️ modified (same address, "
            "different semantics) · ⊘ tombstoned (present but always reverts) · = inherited · "
            "◌ pending · ◐ opt-in per deployment · ⏳ tombstoning scheduled · "
            "‼️ pending allocation conflict · † inherited from a stack ancestor · "
            "? not recorded\n")

def gen_precompiles(chains):
    slugs = order(chains)
    tab, org = addr_rows(chains, "precompiles")
    L = ["# Precompiles across chains", "",
         "Generated by `tools/generate.py` — do not edit by hand.", "",
         "Only addresses that differ from mainnet somewhere are listed; a blank cell means "
         "the chain has no entry at that address (for `0x01`–`0x11` that generally means "
         "mainnet-standard behaviour).", "", header(chains, slugs)]
    for a in sorted(tab, key=sortkey):
        row = [cell(tab[a].get(s), s, org.get((a, s))) for s in slugs]
        nm = entry_label(tab[a].values())
        L.append(f"| `{a}` {nm} | " + " | ".join(row) + " |")
    L.append("\n## Precompiles that cannot be enumerated\n")
    any_dyn = False
    for s in slugs:
        dr = (chains[s].get("precompiles") or {}).get("dynamic_range")
        if isinstance(dr, dict):
            any_dyn = True
            L.append(f"- **{name(chains[s])}** — `{dr.get('pattern','')}`  \n  "
                     f"{' '.join(dr.get('note','').split())}")
    if not any_dyn: L.append("_none_")
    L.append("")
    L.append(legend())
    L.append("## Silent divergences (`severity: high`)\n")
    L.append("Divergences that produce wrong results with no revert, no error and no signal "
             "to the caller — across every section, not just precompiles.\n")
    for s in slugs:
        c = chains[s]
        for sec in ("precompiles", "system_contracts"):
            for a, e in (c.get(sec) or {}).items():
                # address keys only — `mutable_bytecode` sits in the same mapping and
                # is emitted by name below, so iterating everything listed it twice
                if isinstance(e, dict) and str(a).startswith("0x") and e.get("severity") == "high":
                    L.append(f"- **{name(c)} `{a}`** — {' '.join(e.get('note','').split())}")
        for e in (c.get("header_fields") or {}).get("modified") or []:
            if isinstance(e, dict) and e.get("severity") == "high":
                L.append(f"- **{name(c)}** header `{e.get('name', '?')}` — "
                     f"{' '.join(e.get('note','').split())}")
        sc = c.get("system_contracts") or {}
        mb = sc.get("mutable_bytecode") if isinstance(sc, dict) else None
        if isinstance(mb, dict) and mb.get("severity") == "high":
            L.append(f"- **{name(c)}** system-contract bytecode — {' '.join(mb.get('note','').split())}")
    write("PRECOMPILES.md", "\n".join(L) + "\n")

def gen_txtypes(chains):
    slugs = order(chains)
    tab, org = addr_rows(chains, "tx_types")
    L = ["# Transaction types across chains", "",
         "Generated by `tools/generate.py` — do not edit by hand.", "",
         "EIP-2718 type bytes only. Legal range is `0x00`–`0x7f`; `0x80`+ collides with "
         "RLP list prefixes.", "", header(chains, slugs)]
    for a in sorted(tab, key=sortkey):
        row = [cell(tab[a].get(s), s, org.get((a, s))) for s in slugs]
        nm = entry_label(tab[a].values())
        L.append(f"| `{a}` {nm} | " + " | ".join(row) + " |")
    L.append(legend())
    L.append("\n## Transactions with no type byte\n")
    L.append("Chains whose protocol transactions fall outside the EIP-2718 envelope "
             "entirely. An indexer enumerating transactions through the EVM envelope "
             "misses these.\n")
    for s in slugs:
        n = chains[s].get("non_evm_transactions")
        if n:
            # `note:` is optional — a row may carry only entries, and a dangling
            # em dash with nothing after it reads as a missing fact rather than
            # an absent one.
            note = " ".join((n.get("note") or "").split())
            L.append(f"**{name(chains[s])}**" + (f" — {note}" if note else ""))
            for e in n.get("entries", []):
                L.append(f"  - `{e.get('id', '')}` {e['name']}")
            L.append("")
    write("TX-TYPES.md", "\n".join(L) + "\n")

def gen_lineage(chains):
    L = ["# Lineage", "", "Generated by `tools/generate.py` — do not edit by hand.", "",
         "```", "ethereum (baseline — go-ethereum v1.17.5, Osaka)"]
    kids = {}
    for s, c in chains.items():
        kids.setdefault(c["lineage"].get("upstream"), []).append(s)
    def walk(parent, depth):
        for s in order({k: chains[k] for k in kids.get(parent, [])}):
            c = chains[s]
            tag = " [stack, not a chain]" if is_stack(c) else ""
            ver = "no public client" if documented(c) else client(c, "version", "?")
            L.append("  " * depth + f"└── {name(c)} ({ver}, "
                     f"{c.get('baseline_fork', '?')}){tag}")
            walk(s, depth + 1)
    walk("ethereum", 1)
    for s in order(chains):
        c = chains[s]
        if c["lineage"].get("upstream") is None and s != "ethereum":
            L.append(f"\n{name(c)} — no upstream (role: {c['chain']['role']})")
    L += ["```", "", "## Fork mapping to mainnet", "",
          "| Chain | Baseline | How the mapping is established |", "|---|---|---|"]
    for s in order(chains):
        c = chains[s]
        # a documented row may have no fork timeline: with no client there is no
        # source schedule to read, only whatever the docs assert
        note = " ".join(((c.get("forks") or {}).get("note")
                         or c["lineage"].get("note") or "").split())
        L.append(f"| {name(c)} | `{c.get('baseline_fork','—')}` | {note[:190]} |")
    write("LINEAGE.md", "\n".join(L) + "\n")

def gen_matrix(chains):
    slugs = order(chains)
    L = ["# EVM difference matrix", "",
         "Generated by `tools/generate.py` — do not edit by hand.", "",
         "| | " + " | ".join(SHORT.get(s, name(chains[s])) for s in slugs) + " |",
         "|---|" + "---|" * len(slugs)]
    def row(label, fn):
        L.append(f"| {label} | " + " | ".join(str(fn(chains[s], s)) for s in slugs) + " |")
    row("Chain ID", lambda c, s: c["chain"].get("chain_id") or "—")
    row("Role", lambda c, s: c["chain"]["role"])
    row("Upstream", lambda c, s: c["lineage"].get("upstream") or "—")
    row("Baseline fork", lambda c, s: c.get("baseline_fork", "—"))
    row("Client", lambda c, s: ("*none public*" if documented(c)
                                else f"{client(c, 'name')} `{client(c, 'version')}`"))
    def count(c, section, pred):
        return sum(1 for k, v in (c.get(section) or {}).items()
                   if str(k).startswith("0x") and pred(v.get("status", "inherited")))
    row("Custom precompiles", lambda c, s: count(c, "precompiles", lambda x: x == "added") or "0")
    row("Modified precompiles", lambda c, s: count(c, "precompiles", lambda x: x == "modified") or "0")
    row("Tombstoned precompiles", lambda c, s: count(c, "precompiles", lambda x: x == "tombstoned") or "0")
    row("Custom tx types", lambda c, s: count(c, "tx_types", lambda x: x == "added") or "0")
    row("Custom opcodes", lambda c, s: len((c.get("opcodes") or {}).get("added") or []) or "0")
    row("System contracts", lambda c, s: sum(1 for k in (c.get("system_contracts") or {})
                                             if str(k).startswith("0x")) or "0")
    row("Txs outside EIP-2718", lambda c, s: "yes" if c.get("non_evm_transactions") else "no")
    def eip(c, slug, num, neg):
        """Resolution lives in model.eip_status, shared with the website."""
        st, _ = eip_status(chains, slug, num)
        if st == "unrecorded": return "?"
        return "yes" if st == "inherited" else neg
    row("EIP-7702", lambda c, s: eip(c, s, 7702, "**no**"))
    row("Blobs (4844)", lambda c, s: eip(c, s, 4844, "no"))
    row("Metering", lambda c, s: (c.get("fee_model") or {}).get("metering", "—"))
    L.append(legend())

    # --- what can SIGN a transaction: an axis of its own -------------------
    L.append("## Transaction authorization\n")
    L.append("What can *authorize* a transaction — which is not what a precompile can "
             "*verify*. A chain may carry P256VERIFY while a P-256 key cannot move a "
             "single wei; see [SCHEMA.md](SCHEMA.md).\n")
    L.append("`ᴬᶜ` = reachable only through account-abstraction code: the protocol runs "
             "the account's own validator, which decides. `†` = inherited from a stack "
             "ancestor — a chain descending from the OP Stack states only its own deltas, so "
             "OP Mainnet declares nothing here at all.\n")
    L.append("| Chain | Key binding | Signers | Schemes that can authorize |")
    L.append("|---|---|---|---|")
    unpaired = []
    for s in slugs:
        c = chains[s]
        # resolved through a stack ancestor: OP Mainnet declares nothing but a note
        # saying it has no delta, and reading the raw row rendered it as if NO
        # signature could authorize a transaction on it
        fields, schemes, org = tx_auth(chains, s)
        if not schemes:
            L.append(f"| {name(c)} | *inherits upstream* | | |"); continue
        auth = []
        for n, v in schemes.items():
            a = v.get("authorizes")
            # `account_code` still authorizes — the account's own validator decides,
            # rather than the client. Rendering only `protocol` made zkSync, where
            # there is no protocol-level signature check at all, read as if NOTHING
            # could authorize a transaction on it.
            if a not in ("protocol", "account_code"): continue
            pc = v.get("precompile")
            suffix = " ᴬᶜ" if a == "account_code" else ""
            dag = "†" if org.get(n) not in (None, s) else ""
            if a == "protocol" and pc in (None, "none"):
                auth.append(f"**{n}**{dag} ⚠️")
                if org.get(n) in (None, s): unpaired.append((name(c), n, v))
            else:
                auth.append(f"{n}{suffix}{dag}" + (f" (`{pc}`)" if pc not in (None, "none") else ""))
        sig = str(fields.get("signers_per_tx", "—"))
        if len(sig) > 24: sig = sig[:22] + "…"
        kd = "†" if org.get("key_binding") not in (None, s) else ""
        L.append(f"| {name(c)} | `{fields.get('key_binding','—')}`{kd} | "
                 f"{sig} | {', '.join(auth) or '—'} |")
    L.append("")
    L.append("### ⚠️ Authorizes a transaction, with no precompile to verify it\n")
    L.append("The chain accepts transaction signatures its own contracts cannot check. "
             "An on-chain multisig, verifier or recovery contract has no way to validate "
             "what the protocol just accepted.\n")
    real = [(cn, n, v) for cn, n, v in unpaired if n != "unsigned"]
    for cn, n, v in real:
        L.append(f"- **{cn} — `{n}`** — {' '.join(v.get('note','').split())[:300]}")
    L.append("")
    L.append("Entries named `unsigned` are excluded above: a protocol-constructed "
             "transaction carries no signature at all, so `precompile: none` records an "
             "absence of subject matter rather than an unpaired verifier "
             f"({', '.join(cn for cn, n, _ in unpaired if n == 'unsigned')}).\n")

    L.append("## Per-chain gotchas\n")
    for s in slugs:
        c = chains[s]
        L.append(f"### [{name(c)}](chains/{s}/SUMMARY.md)\n")
        for g in (c.get("gotchas") or []):
            L.append(f"- {' '.join(g.split())}")
        L.append("")
    write("MATRIX.md", "\n".join(L) + "\n")

if __name__ == "__main__":
    ch = load()
    print(f"loaded {len(ch)} chain files")
    gen_matrix(ch); gen_precompiles(ch); gen_txtypes(ch); gen_lineage(ch)
