#!/usr/bin/env python3
"""Regenerate the top-level aggregate tables from chains/*/chain.yaml.

Ethereum Mainnet is the Schelling point: every row is a delta against it.
Stack nodes (role: stack) are resolved into their descendants so aggregate
tables show each chain's complete effective set, with origin marked.
"""
import sys, pathlib, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
CHAINS = ROOT / "chains"
# display order: baseline, then stack nodes before their descendants
ORDER = ["ethereum", "bnb", "polygon", "avalanche-c", "avalanche-subnet", "arbitrum",
         "op-stack", "optimism", "base", "worldchain", "opbnb", "tron"]

SHORT = {"ethereum": "Ethereum", "bnb": "BNB", "polygon": "Polygon",
         "avalanche-c": "Avax C", "avalanche-subnet": "Avax subnet", "arbitrum": "Arbitrum",
         "op-stack": "OP Stack", "optimism": "OP Mainnet", "base": "Base",
         "worldchain": "World", "opbnb": "opBNB", "tron": "Tron"}

MARK = {"added": "➕", "removed": "➖", "modified": "⚠️", "inherited": "=",
        "pending": "◌", "tombstoned": "⊘"}

def load():
    out = {}
    for d in sorted(CHAINS.iterdir()):
        f = d / "chain.yaml"
        if f.exists():
            out[d.name] = yaml.safe_load(f.read_text())
    return out

def name(c):   return c["chain"]["name"]
def documented(c): return c["chain"].get("evidence") == "documented"
def client(c, field, dflt="—"):
    """Documented rows carry no client — there is no public one to pin."""
    return (c.get("client") or {}).get(field, dflt)
def is_stack(c): return c["chain"].get("role") == "stack"

def order(chains):
    return [s for s in ORDER if s in chains] + [s for s in chains if s not in ORDER]

def addr_rows(chains, section):
    """Collect address->{slug: entry} across chains, resolving stack inheritance."""
    table, origin = {}, {}
    for slug in order(chains):
        c = chains[slug]
        up = c["lineage"].get("upstream")
        # inherit from a stack ancestor first, then let own entries override
        if up in chains and is_stack(chains[up]):
            for k, v in (chains[up].get(section) or {}).items():
                if not str(k).startswith("0x"): continue
                table.setdefault(k, {})[slug] = v
                origin.setdefault((k, slug), up)
        for k, v in (c.get(section) or {}).items():
            if not str(k).startswith("0x"): continue
            table.setdefault(k, {})[slug] = v
            origin[(k, slug)] = slug
    return table, origin

def sortkey(a):
    try: return (0, int(a, 16))
    except Exception: return (1, 0)

def cell(entry, this_slug, org):
    if entry is None: return ""
    s = MARK.get(entry.get("status", "inherited"), entry.get("status", ""))
    if entry.get("availability") == "optional": s += "◐"
    if entry.get("tombstoned_at"): s += "⏳"
    if entry.get("pending_conflict"): s += "‼️"
    if org and org != this_slug: s += "†"
    return s

def header(chains, slugs):
    h = "| Address | " + " | ".join(SHORT.get(s, name(chains[s])) for s in slugs) + " |"
    return h + "\n|" + "---|" * (len(slugs) + 1)

def write(path, text):
    (ROOT / path).write_text(text)
    print(f"  wrote {path} ({len(text.splitlines())} lines)")

def legend():
    return ("\nLegend: ➕ added · ➖ removed / never adopted · ⚠️ modified (same address, "
            "different semantics) · ⊘ tombstoned (present but always reverts) · = inherited · "
            "◌ pending · ◐ opt-in per deployment · ⏳ tombstoning scheduled · "
            "‼️ pending allocation conflict · † inherited from a stack ancestor · "
            "? not recorded\n")

def gen_precompiles(chains):
    slugs = order(chains)
    tab, org = addr_rows(chains, "precompiles")
    L = ["# Precompiles across chains", "",
         "Generated by `tools/generate.py` — do not edit by hand.", "",
         "Only addresses that differ from mainnet somewhere are listed; a blank cell means "
         "the chain has no entry at that address (for `0x01`–`0x11` that generally means "
         "mainnet-standard behaviour).", "", header(chains, slugs)]
    for a in sorted(tab, key=sortkey):
        row = [cell(tab[a].get(s), s, org.get((a, s))) for s in slugs]
        nm = next((e.get("name", "") for e in tab[a].values() if e.get("name")), "")
        L.append(f"| `{a}` {nm} | " + " | ".join(row) + " |")
    L.append("\n## Precompiles that cannot be enumerated\n")
    any_dyn = False
    for s in slugs:
        dr = (chains[s].get("precompiles") or {}).get("dynamic_range")
        if isinstance(dr, dict):
            any_dyn = True
            L.append(f"- **{name(chains[s])}** — `{dr.get('pattern','')}`  \n  "
                     f"{' '.join(dr.get('note','').split())}")
    if not any_dyn: L.append("_none_")
    L.append("")
    L.append(legend())
    L.append("## Silent divergences (`severity: high`)\n")
    L.append("Divergences that produce wrong results with no revert, no error and no signal "
             "to the caller — across every section, not just precompiles.\n")
    for s in slugs:
        c = chains[s]
        for sec in ("precompiles", "system_contracts"):
            for a, e in (c.get(sec) or {}).items():
                if isinstance(e, dict) and e.get("severity") == "high":
                    L.append(f"- **{name(c)} `{a}`** — {' '.join(e.get('note','').split())}")
        for e in (c.get("header_fields") or {}).get("modified") or []:
            if isinstance(e, dict) and e.get("severity") == "high":
                L.append(f"- **{name(c)}** header `{e.get('name', '?')}` — "
                     f"{' '.join(e.get('note','').split())}")
        sc = c.get("system_contracts") or {}
        mb = sc.get("mutable_bytecode") if isinstance(sc, dict) else None
        if isinstance(mb, dict) and mb.get("severity") == "high":
            L.append(f"- **{name(c)}** system-contract bytecode — {' '.join(mb.get('note','').split())}")
    write("PRECOMPILES.md", "\n".join(L) + "\n")

def gen_txtypes(chains):
    slugs = order(chains)
    tab, org = addr_rows(chains, "tx_types")
    L = ["# Transaction types across chains", "",
         "Generated by `tools/generate.py` — do not edit by hand.", "",
         "EIP-2718 type bytes only. Legal range is `0x00`–`0x7f`; `0x80`+ collides with "
         "RLP list prefixes.", "", header(chains, slugs)]
    for a in sorted(tab, key=sortkey):
        row = [cell(tab[a].get(s), s, org.get((a, s))) for s in slugs]
        nm = next((e.get("name", "") for e in tab[a].values() if e.get("name")), "")
        L.append(f"| `{a}` {nm} | " + " | ".join(row) + " |")
    L.append(legend())
    L.append("\n## Transactions with no type byte\n")
    L.append("Chains whose protocol transactions fall outside the EIP-2718 envelope "
             "entirely. An indexer enumerating transactions through the EVM envelope "
             "misses these.\n")
    for s in slugs:
        n = chains[s].get("non_evm_transactions")
        if n:
            L.append(f"**{name(chains[s])}** — " + " ".join(n.get("note", "").split()))
            for e in n.get("entries", []):
                L.append(f"  - `{e.get('id', '')}` {e['name']}")
            L.append("")
    write("TX-TYPES.md", "\n".join(L) + "\n")

def gen_lineage(chains):
    L = ["# Lineage", "", "Generated by `tools/generate.py` — do not edit by hand.", "",
         "```", "ethereum (baseline — go-ethereum v1.17.5, Osaka)"]
    kids = {}
    for s, c in chains.items():
        kids.setdefault(c["lineage"].get("upstream"), []).append(s)
    def walk(parent, depth):
        for s in order({k: chains[k] for k in kids.get(parent, [])}):
            c = chains[s]
            tag = " [stack, not a chain]" if is_stack(c) else ""
            ver = "no public client" if documented(c) else client(c, "version", "?")
            L.append("  " * depth + f"└── {name(c)} ({ver}, "
                     f"{c.get('baseline_fork', '?')}){tag}")
            walk(s, depth + 1)
    walk("ethereum", 1)
    for s in order(chains):
        c = chains[s]
        if c["lineage"].get("upstream") is None and s != "ethereum":
            L.append(f"\n{name(c)} — no upstream (role: {c['chain']['role']})")
    L += ["```", "", "## Fork mapping to mainnet", "",
          "| Chain | Baseline | How the mapping is established |", "|---|---|---|"]
    for s in order(chains):
        c = chains[s]
        # a documented row may have no fork timeline: with no client there is no
        # source schedule to read, only whatever the docs assert
        note = " ".join(((c.get("forks") or {}).get("note")
                         or c["lineage"].get("note") or "").split())
        L.append(f"| {name(c)} | `{c.get('baseline_fork','—')}` | {note[:190]} |")
    write("LINEAGE.md", "\n".join(L) + "\n")

def gen_matrix(chains):
    slugs = order(chains)
    L = ["# EVM difference matrix", "",
         "Generated by `tools/generate.py` — do not edit by hand.", "",
         "| | " + " | ".join(SHORT.get(s, name(chains[s])) for s in slugs) + " |",
         "|---|" + "---|" * len(slugs)]
    def row(label, fn):
        L.append(f"| {label} | " + " | ".join(str(fn(chains[s], s)) for s in slugs) + " |")
    row("Chain ID", lambda c, s: c["chain"].get("chain_id") or "—")
    row("Role", lambda c, s: c["chain"]["role"])
    row("Upstream", lambda c, s: c["lineage"].get("upstream") or "—")
    row("Baseline fork", lambda c, s: c.get("baseline_fork", "—"))
    row("Client", lambda c, s: ("*none public*" if documented(c)
                                else f"{client(c, 'name')} `{client(c, 'version')}`"))
    def count(c, section, pred):
        return sum(1 for k, v in (c.get(section) or {}).items()
                   if str(k).startswith("0x") and pred(v.get("status", "inherited")))
    row("Custom precompiles", lambda c, s: count(c, "precompiles", lambda x: x == "added") or "0")
    row("Modified precompiles", lambda c, s: count(c, "precompiles", lambda x: x == "modified") or "0")
    row("Tombstoned precompiles", lambda c, s: count(c, "precompiles", lambda x: x == "tombstoned") or "0")
    row("Custom tx types", lambda c, s: count(c, "tx_types", lambda x: x == "added") or "0")
    row("Custom opcodes", lambda c, s: len((c.get("opcodes") or {}).get("added") or []) or "0")
    row("System contracts", lambda c, s: sum(1 for k in (c.get("system_contracts") or {})
                                             if str(k).startswith("0x")) or "0")
    row("Txs outside EIP-2718", lambda c, s: "yes" if c.get("non_evm_transactions") else "no")
    def eip(c, slug, num, neg):
        """Resolve an EIP through stack ancestry. '?' means NOT RECORDED — never
        silently render an unverified fact as a positive claim."""
        e = (c.get("eips") or {}).get(num)
        if e is None:
            up = c["lineage"].get("upstream")
            if up in chains and is_stack(chains[up]):
                e = (chains[up].get("eips") or {}).get(num)
            if e is None:
                return "yes" if c["chain"]["role"] == "baseline" else "?"
        st = e.get("status", "inherited")
        if st == "unrecorded": return "?"
        return "yes" if st == "inherited" else neg
    row("EIP-7702", lambda c, s: eip(c, s, 7702, "**no**"))
    row("Blobs (4844)", lambda c, s: eip(c, s, 4844, "no"))
    row("Metering", lambda c, s: (c.get("fee_model") or {}).get("metering", "—"))
    L.append(legend())
    L.append("## Per-chain gotchas\n")
    for s in slugs:
        c = chains[s]
        L.append(f"### [{name(c)}](chains/{s}/SUMMARY.md)\n")
        for g in (c.get("gotchas") or []):
            L.append(f"- {' '.join(g.split())}")
        L.append("")
    write("MATRIX.md", "\n".join(L) + "\n")

if __name__ == "__main__":
    ch = load()
    print(f"loaded {len(ch)} chain files")
    gen_matrix(ch); gen_precompiles(ch); gen_txtypes(ch); gen_lineage(ch)
